### ISSUE TITLE
ReflectionTypeLoadException - multi-target (net6.0 & net7.0) class library with FrameworkReference

### ISSUE THREAD

**Issue by stand-sure** [ejball/XmlDocMarkdown#128]
Getting the following error
```shell
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at XmlDocMarkdown.Core.MarkdownGenerator.DoGenerateOutput(Assembly assembly, XmlDocAssembly xmlDocAssembly)+MoveNext() in /_/src/XmlDocMarkdown.Core/MarkdownGenerator.cs:line 55
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at XmlDocMarkdown.Core.MarkdownGenerator.GenerateOutput(Assembly assembly, XmlDocAssembly xmlDocAssembly) in /_/src/XmlDocMarkdown.Core/MarkdownGenerator.cs:line 38
   at XmlDocMarkdown.Core.XmlDocMarkdownGenerator.Generate(XmlDocInput input, String outputPath, XmlDocMarkdownSettings settings) in /_/src/XmlDocMarkdown.Core/XmlDocMarkdownGenerator.cs:line 92
   at XmlDocMarkdown.Core.XmlDocMarkdownApp.Run(IReadOnlyList`1 args) in /_/src/XmlDocMarkdown.Core/XmlDocMarkdownApp.cs:line 70
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.AspNetCore.Mvc.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

Not sure if the multiple frameworks targets are messing up the tool or if it is the Framework reference...

csproj fragment
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>

```

**Comment by stand-sure** [comment]
running on a Mac w/ Apple Silicon

**Comment by stand-sure** [comment]
I was able to hack around the issue, but it would be nice if the tool knew to check default locations

```shell
! /usr/bin/env bash
# to install the tool used in this script
# dotnet tool install xmldocmd -g

if [[ "$OSTYPE" == "darwin"* ]] && \
  [[ ! -L ./bin/Debug/net7.0/Microsoft.AspNetCore.Mvc.Core.dll ]] && \
  [[ ! -L ./bin/Debug/net7.0/Microsoft.AspNetCore.Mvc.Abstractions.dll ]] ; then
    
    ln -s /usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.5/Microsoft.AspNetCore.Mvc.Core.dll \
      ./bin/Debug/net7.0/Microsoft.AspNetCore.Mvc.Core.dll
    
    ln -s /usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.5/Microsoft.AspNetCore.Mvc.Abstractions.dll \
      ./bin/Debug/net7.0/Microsoft.AspNetCore.Mvc.Abstractions.dll
fi 

xmldocmd ./bin/Debug/net7.0/MyThing.dll docs/ 
```

**Comment by ejball** [comment]
Sorry about that! See [the Usage section](https://ejball.com/XmlDocMarkdown/#usage) in the documentation for the official workaround.

**Comment by stand-sure** [comment]
@ejball what work around? the only mention of mac is to use mono... ????

**Comment by ejball** [comment]
The workaround is at the beginning of [the Usage section](https://ejball.com/XmlDocMarkdown/#usage): "The most reliable way to use XmlDocMarkdown is to build and run a command-line tool that references the XmlDocMarkdown.Core class library and the assembly that you want to document."
