### ISSUE TITLE
Fails when building docs for ASP Net Core 3.1 projects

### ISSUE THREAD

**Issue by winterscr** [ejball/XmlDocMarkdown#68]
Running the tool via `dotnet xmldocmd` against a project built using ASP Net Core 3.1 fails with the following exception.

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at XmlDocMarkdown.Core.MarkdownGenerator.DoGenerateOutput(Assembly assembly, XmlDocAssembly xmlDocAssembly)+MoveNext() in C:\projects\xmldocmarkdown\src\XmlDocMarkdown.Core\MarkdownGenerator.cs:line 41
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at XmlDocMarkdown.Core.XmlDocMarkdownGenerator.Generate(String inputPath, String outputPath, XmlDocMarkdownSettings settings) in C:\projects\xmldocmarkdown\src\XmlDocMarkdown.Core\XmlDocMarkdownGenerator.cs:line 58
   at XmlDocMarkdown.XmlDocMarkdownApp.Run(IReadOnlyList`1 args) in C:\projects\xmldocmarkdown\src\xmldocmd\XmlDocMarkdownApp.cs:line 55
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

I'm guessing this is due to 3.0+ being pulled in as a framework now rather than NuGet packages so the DLLs aren't in the output folder and the assembly manifest just references the metadata reference assemblies from another folder.

**Comment by winterscr** [comment]
Closing this as #69 better addresses it.

**Comment by manuel-fernandez-rodriguez** [comment]
I solved the `ReflectionTypeLoadException` when loading assembly `Microsoft.AspNetCore.Mvc.Core` by adding a framework reference to my console application .csproj, which uses XmlDocMarkdownGenerator like this:
```xml
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```
From that moment on, the documentation for my asp.net core 3.1 application was successfully generated.

I got the solution from a comment in dotnet/runtime#1050 on a known limitation on `AssemblyDependencyResolver`. 

Not sure if this information could somehow help on #69 as well.

**Comment by ejball** [comment]
Thanks, @manuel-fernandez-rodriguez -- I've recently [made it easier](https://github.com/ejball/XmlDocMarkdown/issues/69#issuecomment-686763869) to use the documentation generator from a console app that has all of the required dependencies.
