### ISSUE TITLE
Visible F#-style extension methods cause failure with NRE

### ISSUE THREAD

**Issue by SteveGilham** [ejball/XmlDocMarkdown#73]
Create a new F# Library project with the following source code
```
namespace ExtensionMethods

open System.Collections
open System.Runtime.CompilerServices

// F# extension style
// implicit `this` parameter has a null name
module Augment =
  type System.Object with
    member self.IsNotNull
      with get() =
        self |> isNull |> not

open Augment

// C# extension style
// no `this` parameter syntactic sugar available
// so explicitly decorate with `ExtensionAttribute`
[<Extension>]
module Utility =
  [<Extension>]
  let SafeLength (x : IEnumerable) =
    if x.IsNotNull
    then  x |> Seq.cast<obj> |> Seq.length
    else -1
```
and run` xmldocmd` over the resulting assembly.  

The following exception results --
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at XmlDocMarkdown.Core.MarkdownGenerator.GetFullSignature(MemberInfo memberInfo, ICollection`1 seeAlsoMembers) in C:\projects\xmldocmarkdown\src\XmlDocMarkdown.Core\MarkdownGenerator.cs:line 874
   at XmlDocMarkdown.Core.MarkdownGenerator.<>c__DisplayClass41_0.<WriteMemberPage>b__0(MarkdownWriter writer) in C:\projects\xmldocmarkdown\src\XmlDocMarkdown.Core\MarkdownGenerator.cs:line 250
   at XmlDocMarkdown.Core.MarkdownGenerator.CreateNamedText(String name, Action`1 writeTo) in C:\projects\xmldocmarkdown\src\XmlDocMarkdown.Core\MarkdownGenerator.cs:line 152
   at XmlDocMarkdown.Core.MarkdownGenerator.WriteMemberPage(String path, IReadOnlyList`1 memberGroup, MarkdownContext context) in C:\projects\xmldocmarkdown\src\XmlDocMarkdown.Core\MarkdownGenerator.cs:line 213
   at XmlDocMarkdown.Core.MarkdownGenerator.DoGenerateOutput(Assembly assembly, XmlDocAssembly xmlDocAssembly)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at XmlDocMarkdown.Core.XmlDocMarkdownGenerator.Generate(String inputPath, String outputPath, XmlDocMarkdownSettings settings) in C:\projects\xmldocmarkdown\src\XmlDocMarkdown.Core\XmlDocMarkdownGenerator.cs:line 58
   at XmlDocMarkdown.XmlDocMarkdownApp.Run(IReadOnlyList`1 args) in C:\projects\xmldocmarkdown\src\xmldocmd\XmlDocMarkdownApp.cs:line 55
```
because the implicit `this` parameter has a null parameter name.

**Comment by SteveGilham** [comment]
Null implicit parameter names are also generated in code like
```
type Fix<'T> = delegate of 'T -> Fix<'T>
```

**Comment by SteveGilham** [comment]
Release 2.1.0 resolves the issue as expected.
